# Generated by Django 5.2.17 on 2026-10-01 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_engine', '0004_expand_media_file_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaProcessingLease',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PanoramaBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=64)),
                ('processor_version', models.PositiveIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('config', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('PROCESSING', 'Processing'), ('PREVIEW_READY', 'Preview ready'), ('BASE_LEVEL_READY', 'Base level ready'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PROCESSING', max_length=24)),
                ('preview', models.FileField(blank=True, max_length=500, upload_to='media_engine/panoramas/')),
                ('manifest', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='panoramatile',
            name='uniq_panorama_tile_version_v2',
        ),
        migrations.AddField(
            model_name='panoramabuild',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_builds', to='media_engine.mediaasset'),
        ),
        migrations.AddField(
            model_name='panoramatile',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='media_engine.panoramabuild'),
        ),
        migrations.AddConstraint(
            model_name='panoramatile',
            constraint=models.UniqueConstraint(condition=models.Q(('build__isnull', True)), fields=('asset', 'profile', 'processor_version', 'level', 'face', 'col', 'row', 'format'), name='uniq_panorama_tile_legacy'),
        ),
        migrations.AddConstraint(
            model_name='panoramatile',
            constraint=models.UniqueConstraint(fields=('build', 'level', 'face', 'col', 'row', 'format'), name='uniq_panorama_build_tile'),
        ),
        migrations.AddIndex(
            model_name='panoramabuild',
            index=models.Index(fields=['asset', 'profile', 'fingerprint'], name='moe_pano_build_lookup'),
        ),
        migrations.AddConstraint(
            model_name='panoramabuild',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('asset', 'profile'), name='uniq_active_panorama_build'),
        ),
    ]
